### ISSUE TITLE
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)>

### ISSUE THREAD

**Issue by 14H034160212** [ppizarror/PyMultiDictionary#9] opened 2021-11-29 21:59 UTC
Hi,

I got this issue when I want to run the program to call the `dictionary.antonym`. It seems the certificate has expired. Does anyone know how to sovle that issue? Thanks.
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)>

**Comment by ppizarror** [comment] 2021-11-29 22:14
Hello. Can you provide a minimal working example? I cannot reproduce your bug :(

<img width="1042" alt="Captura de Pantalla 2021-11-29 a la(s) 19 14 06" src="https://user-images.githubusercontent.com/12925256/143951210-5c444cea-b578-4aa6-9b53-fc8e1c0d26ad.png">

**Comment by ppizarror** [comment] 2021-12-03 16:05
Hello. Any updates, are you obtaining the same error?
I've found this solution https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error, basically, implement an SSL bypass to avoid certificate validation.

Greetings 😄

**Comment by ppizarror** [comment] 2022-01-19 03:59
I'm going to close this issue by now 📦

**Comment by ppizarror** [comment] 2022-02-13 21:38
Fixed in 1.2.0!

**Closed by ppizarror** 2022-02-13 21:38 UTC
Labels: bug
